model:
  size: n
  device: "cpu"
  use_tensorrt: false
inference_size: [ 640, 640 ]
classes: [ 2 ]
max_batch_size: 1
max_batch_interval: 0
log_level: DEBUG
redis:
  host: redis
  port: 6379
  stream_ids:
    - video1