#!/bin/bash
set -e

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then
    echo "Create virtual environment for application"
    cd "/opt/starwit/objectdetector"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install ultralytics==8.3.155 --no-deps
    pip install -r requirements.txt     

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/objectdetector <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/objectdetector
source .venv/bin/activate

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/objectdetector    

    # link settings file from etc
    cd /opt/starwit/objectdetector
    ln -s /etc/starwit/objectdetector/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start objectdetector.service        
    systemctl enable objectdetector.service
fi

#DEBHELPER#

exit 0