#!/bin/bash
set -e

# Install Python packages that aren't available via APT
if [ "$1" = "configure" ]; then
    python -m pip install --user virtualenv
    export PATH=/root/.local/bin:$PATH
    echo "Create virtual environment for application"
    cd "/opt/starwit/objectdetector"
    virtualenv --system-site-packages .venv
    source .venv/bin/activate
    # Libs that can't be installed via requirements file / version conflict
    pip install ultralytics==8.3.167 --no-deps
    pip install pyturbojpeg
    pip install -r requirements.txt

    # Download standard model
    wget https://github.com/ultralytics/assets/releases/download/v8.3.0/yolov8m.pt -O /opt/starwit/objectdetector/yolov8m.pt   

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/objectdetector <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/objectdetector
source .venv/bin/activate

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/objectdetector    

    # link settings file from etc
    cd /opt/starwit/objectdetector
    ln -s /etc/starwit/objectdetector/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start objectdetector.service        
    systemctl enable objectdetector.service
fi

#DEBHELPER#

exit 0