#!/bin/bash
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then

    # Stop the service
    systemctl stop objectdetector.service

    # Disable the service
    systemctl disable objectdetector.service

    # Remove the service file
    rm -f /etc/systemd/system/objectdetector.service

    systemctl daemon-reload

    # Remove the wrapper script
    rm -f /usr/local/bin/objectdetector
    
    # Remove application directory
    rm -rf /opt/starwit/objectdetector

    # Remove config files directory
    rm -rf /etc/starwit/objectdetector
fi

#DEBHELPER#

exit 0